# Generated by Django 4.2 on 2023-05-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_schedule_slot_alter_schedule_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_date',
            field=models.DateField(verbose_name='Дата лекции'),
        ),
    ]
