# Generated by Django 4.2 on 2023-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_lecture_lecture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='attestation_date',
            field=models.DateField(blank=True, verbose_name='Дата аттестации'),
        ),
    ]
