# Generated by Django 4.2 on 2023-04-25 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 25, 13, 34, 29, 639791)),
        ),
    ]
