# Generated by Django 4.2 on 2023-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lecture_number_in_lmk',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=1, null=True, verbose_name='Номер обучения в ЛМК'),
        ),
    ]
