# Generated by Django 4.2 on 2023-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_programs', '0002_alter_programsubcategories_category'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sub_categories',
            field=models.ManyToManyField(related_name='teacher_sub_category', to='educational_programs.programsubcategories'),
        ),
    ]
