# Generated by Django 4.2 on 2023-05-15 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_remove_lecture_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0002_alter_teacher_sub_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Часы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Пометка на удаление')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_lecture', to='schedule.lecture')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_teacher', to='teacher.teacher')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Внутренний пользователь')),
            ],
            options={
                'verbose_name': 'Workload',
                'verbose_name_plural': 'Workloads',
                'db_table': 'workload',
            },
        ),
    ]
